import ExcelJS from "exceljs";
import path from "path";

export const createExcelFile = async ({
    sheetName,
    title,
    columns,
    rows,
    generatedBy = "Dinesh Kumar"
}) => {

    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet(sheetName);

    // =========================
    // COLUMN WIDTHS
    // =========================

    columns.forEach((column, index) => {
        worksheet.getColumn(index + 1).width = column.width;
    });

    // =========================
    // COMMON TOP HEADER
    // =========================

    worksheet.mergeCells("A1:C2");
    worksheet.mergeCells("D1:F2");
    worksheet.mergeCells("G1:I2");

    // =========================
    // LOGO
    // =========================

    const logoId = workbook.addImage({
        filename: path.resolve("assets", "emlogo.png"),
        extension: "png"
    });

    worksheet.addImage(logoId, {
        tl: {
            col: 0.7,
            row: 0.2
        },
        ext: {
            width: 70,
            height: 40
        }
    });

    // =========================
    // DATE & TIME
    // =========================

    const now = new Date();

    const date = now.toLocaleDateString("en-IN", {
        day: "2-digit",
        month: "2-digit",
        year: "numeric"
    });

    const time = now.toLocaleTimeString("en-IN", {
        hour: "2-digit",
        minute: "2-digit",
        second: "2-digit",
        hour12: true
    });

    // =========================
    // TITLE
    // =========================

    const titleCell = worksheet.getCell("D1");

    titleCell.value = title;

    titleCell.font = {
        name: "Arial",
        size: 16,
        bold: true
    };

    titleCell.alignment = {
        horizontal: "center",
        vertical: "middle"
    };

    // =========================
    // GENERATED INFO
    // =========================

    const infoCell = worksheet.getCell("G1");

    infoCell.value =
        `Generated By: ${generatedBy}\n` +
        `Date: ${date}   ${time}`;

    infoCell.font = {
        name: "Arial",
        size: 10
    };

    infoCell.alignment = {
        horizontal: "center",
        vertical: "middle",
        wrapText: true
    };

    worksheet.getRow(1).height = 30;
    worksheet.getRow(2).height = 25;

    // =========================
    // TABLE HEADER - ROW 4
    // =========================

    const headerRow = worksheet.getRow(4);

    columns.forEach((column, index) => {

        const cell = headerRow.getCell(index + 1);

        cell.value = column.header;

        cell.font = {
            name: "Arial",
            size: 10,
            bold: true
        };

        cell.alignment = {
            horizontal: "center",
            vertical: "middle"
        };

        cell.border = {
            top: { style: "thin" },
            bottom: { style: "thin" },
            left: { style: "thin" },
            right: { style: "thin" }
        };
    });

    headerRow.height = 25;

    // =========================
    // DATA
    // =========================

    rows.forEach(data => {

        const row = worksheet.addRow(data);

        row.eachCell(cell => {

            cell.font = {
                name: "Arial",
                size: 10
            };

            cell.alignment = {
                vertical: "middle"
            };

            cell.border = {
                top: { style: "thin" },
                bottom: { style: "thin" },
                left: { style: "thin" },
                right: { style: "thin" }
            };
        });
    });

    // =========================
    // FREEZE
    // =========================

    worksheet.views = [
        {
            state: "frozen",
            ySplit: 4
        }
    ];

    return workbook;
};