import PDFDocument from "pdfkit";
import path from "path";

export const exportPDF = ({
    res,
    title,
    fileName,
    headers,
    columnWidths,
    rows,
    generatedBy = "Dinesh Kumar"
}) => {

    const doc = new PDFDocument({
        size: "A4",
        layout: "landscape",
        margin: 30,
        bufferPages: true
    });

    // =========================
    // RESPONSE
    // =========================

    res.setHeader(
        "Content-Type",
        "application/pdf"
    );

    res.setHeader(
        "Content-Disposition",
        `attachment; filename="${fileName}"`
    );

    doc.pipe(res);

    // =========================
    // PAGE CONSTANTS
    // =========================

    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;

    const leftMargin = 44;
    const rightMargin = 44;

    const headerTop = 20;
    const rowHeight = 28;

    const tableStartY = 90;

    // Keep footer separate from table
    const footerHeight = 30;

    const tableBottom =
        pageHeight - footerHeight;

    // =========================
    // DATE & TIME
    // =========================

    const generatedAt = new Date();

    const generatedDate =
        generatedAt.toLocaleDateString("en-IN", {
            day: "2-digit",
            month: "2-digit",
            year: "numeric"
        });

    const generatedTime =
        generatedAt.toLocaleTimeString("en-IN", {
            hour: "2-digit",
            minute: "2-digit",
            second: "2-digit",
            hour12: true
        });

    // =========================
    // TABLE WIDTH
    // =========================

    const tableWidth = columnWidths.reduce(
        (total, width) => total + width,
        0
    );

    const startX =
        (pageWidth - tableWidth) / 2;

    // =========================
    // HEADER
    // =========================

    const drawHeader = () => {

        const logoPath = path.resolve(
            "assets",
            "emlogo.png"
        );

        doc.image(
            logoPath,
            leftMargin,
            headerTop,
            {
                fit: [75, 40],
                align: "left",
                valign: "center"
            }
        );

        // Title
        doc
            .font("Helvetica-Bold")
            .fontSize(18)
            .text(
                title,
                0,
                headerTop + 10,
                {
                    width: pageWidth,
                    align: "center",
                    lineBreak: false
                }
            );

        // Generated By
        const rightStart =
            pageWidth - 230;

        doc
            .font("Helvetica")
            .fontSize(9)
            .text(
                `Generated By: ${generatedBy}`,
                rightStart,
                headerTop + 10,
                {
                    width: 200,
                    align: "right",
                    lineBreak: false
                }
            );

        // Date
        doc
            .font("Helvetica")
            .fontSize(9)
            .text(
                `Date: ${generatedDate}    ${generatedTime}`,
                pageWidth - 430,
                headerTop + 26,
                {
                    width: 400,
                    align: "right",
                    lineBreak: false
                }
            );

        // Header line
        doc
            .moveTo(
                leftMargin,
                75
            )
            .lineTo(
                pageWidth - rightMargin,
                75
            )
            .lineWidth(1)
            .stroke();
    };

    // =========================
    // TABLE HEADER
    // =========================

    const drawTableHeader = (startY) => {

        let x = startX;

        doc
            .font("Helvetica-Bold")
            .fontSize(9);

        headers.forEach((header, index) => {

            doc
                .rect(
                    x,
                    startY,
                    columnWidths[index],
                    rowHeight
                )
                .stroke();

            doc.text(
                header,
                x + 5,
                startY + 9,
                {
                    width:
                        columnWidths[index] - 10,

                    height:
                        rowHeight - 10,

                    align: "center",

                    lineBreak: false
                }
            );

            x += columnWidths[index];
        });

        return startY + rowHeight;
    };

    // =========================
    // DRAW HEADER
    // =========================

    drawHeader();

    let y =
        drawTableHeader(tableStartY);

    // =========================
    // TABLE DATA
    // =========================

    rows.forEach((values, rowIndex) => {

        // Check whether current row fits
        if (
            y + rowHeight >
            tableBottom
        ) {

            // Only create a new page
            // when there are remaining records
            doc.addPage();

            drawHeader();

            y =
                drawTableHeader(tableStartY);
        }

        let x = startX;

        values.forEach(
            (value, columnIndex) => {

                doc
                    .rect(
                        x,
                        y,
                        columnWidths[columnIndex],
                        rowHeight
                    )
                    .stroke();

                doc
                    .font("Helvetica")
                    .fontSize(8.5)
                    .text(
                        String(value ?? "-"),
                        x + 5,
                        y + 9,
                        {
                            width:
                                columnWidths[columnIndex] - 10,

                            height:
                                rowHeight - 8,

                            align:
                                columnIndex === 0 ||
                                    columnIndex === values.length - 1
                                    ? "center"
                                    : "left",

                            lineBreak: false,

                            ellipsis: true
                        }
                    );

                x += columnWidths[columnIndex];
            }
        );

        y += rowHeight;
    });

    // =========================
    // NO DATA
    // =========================

    if (rows.length === 0) {

        doc
            .font("Helvetica")
            .fontSize(10)
            .text(
                "No data found.",
                startX,
                y + 15,
                {
                    width: tableWidth,
                    align: "center",
                    lineBreak: false
                }
            );
    }

    // =========================
    // FOOTER
    // =========================

    const range =
        doc.bufferedPageRange();

    const totalPages =
        range.count;

    for (
        let i = 0;
        i < totalPages;
        i++
    ) {

        doc.switchToPage(i);

        doc
            .font("Helvetica")
            .fontSize(8)
            .text(
                `Page ${i + 1} of ${totalPages}`,
                0,
                pageHeight - 25,
                {
                    width: pageWidth,
                    height: 10,
                    align: "center",
                    lineBreak: false
                }
            );
    }

    // =========================
    // END
    // =========================

    doc.end();
};